/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'variant-names': VariantName;
    'variant-values': VariantValue;
    products: Product;
    orders: Order;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'variant-names': VariantNamesSelect<false> | VariantNamesSelect<true>;
    'variant-values': VariantValuesSelect<false> | VariantValuesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    company: Company;
    'web-contents': WebContent;
  };
  globalsSelect: {
    company: CompanySelect<false> | CompanySelect<true>;
    'web-contents': WebContentsSelect<false> | WebContentsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category name
   */
  name: string;
  /**
   * URL-friendly identifier for the category
   */
  slug: string;
  /**
   * Category description
   */
  description?: string | null;
  /**
   * Category image
   */
  image?: (number | null) | Media;
  /**
   * Mark as featured category
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-names".
 */
export interface VariantName {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-values".
 */
export interface VariantValue {
  id: number;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The main product title
   */
  title: string;
  /**
   * URL-friendly identifier for the product
   */
  slug: string;
  /**
   * Detailed product description
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief product description for listings
   */
  shortDescription?: string | null;
  /**
   * Primary category for this product
   */
  category?: (number | null) | Category;
  /**
   * Primary image (Will be used as thumbnail)
   */
  coverImage?: (number | null) | Media;
  /**
   * Additional images for product preview
   */
  previewImages?: (number | Media)[] | null;
  /**
   * Base price for the product (before variants)
   */
  basePrice: number;
  variants?:
    | {
        options?:
          | {
              /**
               * Select the variant name for this variant
               */
              variantName?: string | null;
              /**
               * Select the variant value for this variant
               */
              variantValue?: string | null;
              id?: string | null;
            }[]
          | null;
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether the product is active and visible to customers
   */
  isActive?: boolean | null;
  /**
   * SEO settings for this product
   */
  seo?: {
    /**
     * SEO title (if different from product title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  /**
   * Configure custom upload fields for customers to upload their images/designs
   */
  uploadFields?:
    | {
        /**
         * Label for the upload field (e.g., "Upload Logo", "Upload Design")
         */
        label: string;
        /**
         * Make this upload field required for customers
         */
        required?: boolean | null;
        /**
         * Additional instructions for customers (e.g., "PNG, JPG up to 10MB")
         */
        description?: string | null;
        /**
         * Maximum number of files allowed for this field
         */
        maxFiles?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order number
   */
  orderNumber: string;
  /**
   * Session ID of the cart that was converted to this order
   */
  cartSessionId?: string | null;
  /**
   * Items in the order
   */
  items?:
    | {
        /**
         * Reference to the product
         */
        product: number | Product;
        /**
         * Selected variant options for this product
         */
        selectedVariant?:
          | {
              variantName: string;
              variantValue: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Price at the time of order
         */
        price: number;
        /**
         * Quantity of this item ordered
         */
        quantity: number;
        /**
         * Custom files uploaded by the customer for this item
         */
        uploadedFiles?:
          | {
              /**
               * Label of the upload field
               */
              fieldLabel: string;
              /**
               * Files uploaded by the customer
               */
              files?: (number | Media)[] | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total number of items in the order
   */
  totalItems: number;
  /**
   * Total amount of the order
   */
  totalAmount: number;
  /**
   * Current status of the order
   */
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  /**
   * Customer information
   */
  customerInfo: {
    /**
     * Customer full name
     */
    name: string;
    /**
     * Customer email address
     */
    email: string;
    /**
     * Customer phone number
     */
    phone?: string | null;
  };
  /**
   * Shipping address
   */
  shippingAddress: {
    /**
     * Street address
     */
    street: string;
    /**
     * City
     */
    city: string;
    /**
     * State/Province
     */
    state: string;
    /**
     * Postal/ZIP code
     */
    postalCode: string;
    /**
     * Country
     */
    country: string;
  };
  /**
   * Billing address
   */
  billingAddress?: {
    /**
     * Use shipping address for billing
     */
    sameAsShipping?: boolean | null;
    /**
     * Street address
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State/Province
     */
    state?: string | null;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Country
     */
    country?: string | null;
  };
  /**
   * Payment status
   */
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Internal notes about the order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'variant-names';
        value: number | VariantName;
      } | null)
    | ({
        relationTo: 'variant-values';
        value: number | VariantValue;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-names_select".
 */
export interface VariantNamesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-values_select".
 */
export interface VariantValuesSelect<T extends boolean = true> {
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  coverImage?: T;
  previewImages?: T;
  basePrice?: T;
  variants?:
    | T
    | {
        options?:
          | T
          | {
              variantName?: T;
              variantValue?: T;
              id?: T;
            };
        price?: T;
        id?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  uploadFields?:
    | T
    | {
        label?: T;
        required?: T;
        description?: T;
        maxFiles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  cartSessionId?: T;
  items?:
    | T
    | {
        product?: T;
        selectedVariant?:
          | T
          | {
              variantName?: T;
              variantValue?: T;
              id?: T;
            };
        price?: T;
        quantity?: T;
        uploadedFiles?:
          | T
          | {
              fieldLabel?: T;
              files?: T;
              id?: T;
            };
        id?: T;
      };
  totalItems?: T;
  totalAmount?: T;
  status?: T;
  customerInfo?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        sameAsShipping?: T;
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  paymentStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  name: string;
  /**
   * The logo of the company
   */
  logo?: (number | null) | Media;
  /**
   * A short tagline or slogan for your company
   */
  tagline?: string | null;
  /**
   * A brief description of your company
   */
  description?: string | null;
  contactInfo: {
    primaryEmail: string;
    /**
     * Additional email address (e.g., customer care)
     */
    secondaryEmail?: string | null;
    /**
     * Main support phone number displayed prominently
     */
    primaryPhone: string;
    secondaryPhone?: string | null;
    mobilePhone?: string | null;
    /**
     * Complete office address for footer display
     */
    address: string;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    country?: string | null;
  };
  socialMedia?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  businessInfo?: {
    founded?: string | null;
    industry?: string | null;
    size?: ('1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1000+') | null;
    /**
     * For internal use only
     */
    taxId?: string | null;
  };
  seo?: {
    /**
     * Default title for SEO (can be overridden on individual pages)
     */
    metaTitle?: string | null;
    /**
     * Default description for SEO (can be overridden on individual pages)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contents".
 */
export interface WebContent {
  id: number;
  /**
   * The hero image of the website
   */
  heroImage?: (number | null) | Media;
  featuredProducts?: (number | Product)[] | null;
  /**
   * The hero image of the top sellers section
   */
  topSellerHero?: (number | null) | Media;
  topSellerProducts?: (number | Product)[] | null;
  partnerLogos?: (number | Media)[] | null;
  /**
   * The hero image of the best deals section
   */
  bestDealsHero?: (number | null) | Media;
  bestDealsProducts?: (number | Product)[] | null;
  footerContent?: {
    aboutDescription?: string | null;
    freeProofsDescription?: string | null;
    businessHoursDescription?: string | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  tagline?: T;
  description?: T;
  contactInfo?:
    | T
    | {
        primaryEmail?: T;
        secondaryEmail?: T;
        primaryPhone?: T;
        secondaryPhone?: T;
        mobilePhone?: T;
        address?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
      };
  businessInfo?:
    | T
    | {
        founded?: T;
        industry?: T;
        size?: T;
        taxId?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contents_select".
 */
export interface WebContentsSelect<T extends boolean = true> {
  heroImage?: T;
  featuredProducts?: T;
  topSellerHero?: T;
  topSellerProducts?: T;
  partnerLogos?: T;
  bestDealsHero?: T;
  bestDealsProducts?: T;
  footerContent?:
    | T
    | {
        aboutDescription?: T;
        freeProofsDescription?: T;
        businessHoursDescription?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}